---
- name: play
  hosts: localhost
  vars_files: 
    - credentials.yml
  tasks:

## Git configuration
    - name: "Git | Set user.email"
      community.general.git_config:
        name: user.email
        scope: global
        value:  "{{ git_personal_email }}"
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "Git | Set user.name"
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_username }}"
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: Create .ssh directory
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy personal_rsa Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/personal_rsa.pub"
        content: "{{ ssh_key_personal_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy personal_rsa Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/personal_rsa"
        content: "{{ ssh_key_personal_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy work_rsa Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/work_rsa.pub"
        content: "{{ ssh_key_work_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy work_rsa Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/work_rsa"
        content: "{{ ssh_key_work_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy temp Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/temp.pub"
        content: "{{ ssh_key_temp_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy temp Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/temp"
        content: "{{ ssh_key_temp_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: Start SSH agent
      shell: eval $(ssh-agent -s)
      register: ssh_agent_output
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux
    
    - name: Clone repository
      shell: rm -rf ~/.dotfiles && GIT_SSH_COMMAND="ssh -i ~/.ssh/temp" git clone git@github.com:{{ git_username }}/.dotfiles.git ~/.dotfiles
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux
      notify: Run post-stow configuration


## GNU Stow
    - name: "MacOS | Install GNU Stow"
      homebrew:
        name: stow
        state: present
      tags:
        - mac-minimal
        - mac-full
  
    - name: "Debian | Install GNU Stow"
      apt:
        name: stow
        state: present
      become: true
      tags:
        - linux


##
    - name: Check if post_stow_import.yml exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.dotfiles/post_stow.yml"
      register: playbook_file_exist
        - mac-minimal
        - mac-full
        - linux


##
#- name: Run post-stow configuration
#  import_playbook: "post_stow_import.yml"
#  when: playbook_file_exist.stat.exists

##
- name: Run post-stow configuration
  import_playbook: "{{ lookup('env', 'HOME') }}/.dotfiles/post_stow.yml"
  when: playbook_file_exist.stat.exists
