---
- name: play
  hosts: localhost
  vars_files: 
    - credentials.yml
  tasks:

## Git configuration
    - name: "Git | Set user.email"
      community.general.git_config:
        name: user.email
        scope: global
        value:  !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61316532313262376330363766626639376133373432323863383663376562646637363061653331
          3738346136303339326130323934316531333464646334650a346463363431323562383965366232
          65336534356630303063626265663965666130306465373136303031616438613538363762356338
          3331306234643536630a653439326530303931396535333662383466633439626435613434306363
          33386661353633316335376634353861646436613864363531366365333131323737
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "Git | Set user.name"
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_username }}"
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: Create .ssh directory
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy personal_rsa Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/personal_rsa.pub"
        content: "{{ ssh_key_personal_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy personal_rsa Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/personal_rsa"
        content: "{{ ssh_key_personal_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy work_rsa Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/work_rsa.pub"
        content: "{{ ssh_key_work_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy work_rsa Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/work_rsa"
        content: "{{ ssh_key_work_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy temp Public SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/temp.pub"
        content: "{{ ssh_key_temp_public }}"
        mode: '0644'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "SSH | Copy temp Private SSH key"
      copy:
        dest: "{{ ansible_user_dir }}/.ssh/temp"
        content: "{{ ssh_key_temp_private }}"
        mode: '0600'
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: Start SSH agent
      shell: eval $(ssh-agent -s)
      register: ssh_agent_output
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux
    
    - name: Clone repository
      shell: rm -rf ~/.dotfiles && GIT_SSH_COMMAND="ssh -i ~/.ssh/temp" git clone git@github.com:{{ git_username }}/.dotfiles.git ~/.dotfiles
      become: false
      tags:
        - mac-minimal
        - mac-full
        - linux

####

## GNU Stow
    - name: "MacOS | Install GNU Stow"
      homebrew:
        name: stow
        state: present
      tags:
        - mac-minimal
        - mac-full
  
    - name: "Debian | Install GNU Stow"
      apt:
        name: stow
        state: present
      become: true
      tags:
        - linux

- name: Run post-stow configuration
  import_playbook: post_stow.yml
