---
- name: play
  hosts: localhost
  tasks:

# 1Password
    - name: Uninstall 1Password CLI
      ansible.builtin.apt:
        name: 1password-cli
        state: absent
      tags:
        - linux

    - name: Uninstall 1Password and 1Password CLI
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - 1password
        - 1password-cli
      tags:
        - mac

    - name: Uninstall Neovim and its dependencies
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - neovim
        - libtool
        - ansible-lint
        - ripgrep
        - lua
        - luarocks
        - luajit
      tags:
        - mac

    - name: Uninstall Neovim and its dependencies
      ansible.builtin.apt:
        name:
          - neovim
          - pkg-config
          - libtool
          - ansible-lint
          - ripgrep
          - lua5.1
          - luarocks
          - luajit
        state: absent
      tags:
        - linux

    - name: Remove Neovim config folder
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: absent
      tags:
        - linux
        - mac

    - name: Uninstall tmux
      homebrew:
        name: tmux
        state: absent
      tags:
        - mac

    - name: Remove tmux config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux.conf"
        state: absent
      tags:
        - linux
        - mac

    - name: Remove Zsh and oh-my-zsh
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - zsh
      tags:
        - mac

    - name: Remove Zsh config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zshrc"
        state: absent
      tags:
        - mac
        - linux


# Remove zsh & oh-my-zsh
    - name: Remove Oh My Zsh Install Script
      ansible.builtin.file:
        path: /tmp/oh-my-zsh.install.sh
        state: absent
      tags:
        - mac
        - linux

    - name: Cleanup Oh My Zsh Install Script
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/oh-my-zsh.install.sh"
        state: absent
      tags:
        - mac
        - linux
