---
- name: play
  hosts: localhost
  tasks:

# 1Password
    - name: Uninstall 1Password CLI
      ansible.builtin.apt:
        name: 1password-cli
        state: absent
      tags:
        - linux

    - name: Uninstall 1Password and 1Password CLI
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - 1password
        - 1password-cli
      tags:
        - mac

    - name: Uninstall Neovim and its Dependencies
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - neovim
        - libtool
        - ansible-lint
        - ripgrep
        - luarocks
        - luajit
        - lua
      tags:
        - mac

    - name: Uninstall Neovim and its Dependencies
      ansible.builtin.apt:
        name:
          - neovim
          - pkg-config
          - libtool
          - ansible-lint
          - ripgrep
          - luarocks
          - luajit
          - lua5.1
        state: absent
      tags:
        - linux

    - name: Remove Neovim config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: absent
      tags:
        - linux
        - mac

    - name: Uninstall tmux
      homebrew:
        name: tmux
        state: absent
      tags:
        - mac

    - name: Uninstall tmux
      ansible.builtin.apt:
        name: tmux
        state: absent
      tags:
        - linux

    - name: Remove tmux config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux.conf"
        state: absent
      tags:
        - linux
        - mac

    - name: Uninstall Zsh
      ansible.builtin.apt:
        name: zsh
        state: absent
      tags:
        - linux

    - name: Remove Zsh config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zshrc"
        state: absent
      tags:
        - mac
        - linux

    - name: Remove .oh-my-zsh directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
        state: absent
      tags:
        - mac
        - linux
