---
- name: play
  hosts: localhost
  tasks:

## 1Password
    - name: "MacOS | Uninstall 1Password and 1Password CLI"
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - 1password
        - 1password-cli
      tags:
        - mac


# kitty
    - name: "MacOS | Uninstall Kitty terminal emulator"
      homebrew:
        name: kitty
        state: absent
      tags:
        - mac


## neovim
    - name: "MacOS | Uninstall Neovim and its Dependencies"
      homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - neovim
        - libtool
        - ansible-lint
        - ripgrep
        - luarocks
        - luajit
        - lua
      tags:
        - mac

    - name: "Debian | Uninstall Neovim and its Dependencies"
      ansible.builtin.apt:
        name:
          - neovim
          - pkg-config
          - libtool
          - ansible-lint
          - ripgrep
          - luarocks
          - luajit
          - lua5.1
        state: absent
      tags:
        - linux

    - name: Remove Neovim config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: absent
      tags:
        - linux
        - mac

## Remove the configs repo
    - name: Remove .dotfiles directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.dotfiles"
        state: absent
      tags:
        - linux
        - mac
        
 ##stow
    - name: "Unstow Zsh configuration"
      ansible.builtin.command:
        cmd: "stow -D -d {{ ansible_user_dir }}/.dotfiles -t {{ ansible_env.HOME }} zsh"
      tags:
        - mac-minimal
        - mac-full
        - linux

    - name: "Unstow Tmux configuration"
      ansible.builtin.command:
         cmd: "stow -D -d {{ ansible_user_dir }}/.dotfiles -t {{ ansible_env.HOME }} tmux"
      tags:
        - mac-minimal
        - mac-full
        - linux 
        
## tmux
    - name: "MacOS | Uninstall tmux"
      homebrew:
        name: tmux
        state: absent
      tags:
        - mac

    - name: "Debian | Uninstall tmux"
      ansible.builtin.apt:
        name: tmux
        state: absent
      tags:
        - linux

    - name: Remove TPM directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
        state: absent
      tags:
        - linux
        - mac

    - name: Remove tmux config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/tmux.conf"
        state: absent
      tags:
        - linux
        - mac


## zsh
    - name: "Debian | Uninstall Zsh"
      ansible.builtin.apt:
        name: zsh
        state: absent
      tags:
        - linux

    - name: Remove Zsh config
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zshrc"
        state: absent
      tags:
        - mac
        - linux

    - name: Remove .oh-my-zsh directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
        state: absent
      tags:
        - mac
        - linux
